name: NotMeXboxLiveAuth
main: Johnmacrocraft\NotMeXboxLiveAuth\NotMeXboxLiveAuth
version: 1.1.2
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0]
load: POSTWORLD
author: Johnmacrocraft
description: Allows specified players to bypass Xbox Live Auth!
website: https://github.com/Johnmacrocraft/NotMeXboxLiveAuth
commands:
  xboxlist:
    description: Manages the list of players allowed to bypass Xbox Live Auth
    usage: /xboxlist <add|remove|list|invert|prefix|reload>
    permission: notmexboxliveauth.command.xboxlist
permissions:
  notmexboxliveauth:
    description: Allows the use of all the NotMeXboxLiveAuth permissions
    default: op
    children:
      notmexboxliveauth.command:
        description: Allows the use of all the NotMeXboxLiveAuth commands
        default: op
        children:
          notmexboxliveauth.command.xboxlist:
            description: Allows the use of xboxlist command
            default: op
            children:
              notmexboxliveauth.command.xboxlist.add:
                description: Allows the use of add option of xboxlist command
                default: op
              notmexboxliveauth.command.xboxlist.remove:
                description: Allows the use of remove option of xboxlist command
                default: op
              notmexboxliveauth.command.xboxlist.list:
                description: Allows the use of list option of xboxlist command
                default: op
              notmexboxliveauth.command.xboxlist.invert:
                description: Allows the use of invert option of xboxlist command
                default: op
              notmexboxliveauth.command.xboxlist.prefix:
                description: Allows the use of prefix option of xboxlist command
                default: op
              notmexboxliveauth.command.xboxlist.reload:
                description: Allows the use of reload option of xboxlist command
                default: op
